name: Run CURL Command

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1


      - name: Call Curl Command
        id: call-curl-command
        run: |
          json_response=$(curl -s -X GET "https://dummyjson.com/products" \
          -H "Content-Type: application/json")
          echo "::set-output name=json_response::$json_response"

      - name: Set environment variable from JSON
        run: |
            first_product_title=${{ fromJson(steps.call-curl-command.outputs.json_response).products[0].title }} 
            echo "FIRST_PRODUCT_TITLE=$first_product_title" >> $GITHUB_ENV

      - name: Display environment variable
        run: echo "FIRST_PRODUCT_TITLE is ${{ env.FIRST_PRODUCT_TITLE }}"