name: Run CURL Command

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Call curl command
        id: call-curl-command
        run: |
          json_response=$(curl -s -X GET "https://dummyjson.com/products" \
                    -H "Content-Type: application/json")
          echo "::set-output name=json_response::$json_response"

      - name: Set environment variable from JSON
        run: |
          first_product_id=${{ fromJSON(steps.call-curl-command.outputs.json_response).products[0].id }}
          echo "FIRST_PRODUCT_ID=$first_product_id" >> $GITHUB_ENV

      - name : Printout the variable
        run: echo "First product id is ${{ env.FIRST_PRODUCT_ID }}"